// Auto-generated. Do not edit!

// (in-package kinova_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class PoseAndSizeGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.object_pose = null;
      this.object_size = null;
      this.object_class = null;
    }
    else {
      if (initObj.hasOwnProperty('object_pose')) {
        this.object_pose = initObj.object_pose
      }
      else {
        this.object_pose = new geometry_msgs.msg.PointStamped();
      }
      if (initObj.hasOwnProperty('object_size')) {
        this.object_size = initObj.object_size
      }
      else {
        this.object_size = new geometry_msgs.msg.Point();
      }
      if (initObj.hasOwnProperty('object_class')) {
        this.object_class = initObj.object_class
      }
      else {
        this.object_class = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PoseAndSizeGoal
    // Serialize message field [object_pose]
    bufferOffset = geometry_msgs.msg.PointStamped.serialize(obj.object_pose, buffer, bufferOffset);
    // Serialize message field [object_size]
    bufferOffset = geometry_msgs.msg.Point.serialize(obj.object_size, buffer, bufferOffset);
    // Serialize message field [object_class]
    bufferOffset = _serializer.string(obj.object_class, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PoseAndSizeGoal
    let len;
    let data = new PoseAndSizeGoal(null);
    // Deserialize message field [object_pose]
    data.object_pose = geometry_msgs.msg.PointStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [object_size]
    data.object_size = geometry_msgs.msg.Point.deserialize(buffer, bufferOffset);
    // Deserialize message field [object_class]
    data.object_class = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PointStamped.getMessageSize(object.object_pose);
    length += object.object_class.length;
    return length + 28;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kinova_msgs/PoseAndSizeGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4c6131538507f7479aa2828d565cd71a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    geometry_msgs/PointStamped object_pose
    geometry_msgs/Point object_size
    string object_class
    
    ================================================================================
    MSG: geometry_msgs/PointStamped
    # This represents a Point with reference coordinate frame and timestamp
    Header header
    Point point
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PoseAndSizeGoal(null);
    if (msg.object_pose !== undefined) {
      resolved.object_pose = geometry_msgs.msg.PointStamped.Resolve(msg.object_pose)
    }
    else {
      resolved.object_pose = new geometry_msgs.msg.PointStamped()
    }

    if (msg.object_size !== undefined) {
      resolved.object_size = geometry_msgs.msg.Point.Resolve(msg.object_size)
    }
    else {
      resolved.object_size = new geometry_msgs.msg.Point()
    }

    if (msg.object_class !== undefined) {
      resolved.object_class = msg.object_class;
    }
    else {
      resolved.object_class = ''
    }

    return resolved;
    }
};

module.exports = PoseAndSizeGoal;
