// Auto-generated. Do not edit!

// (in-package kinova_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class PoseAndSizeFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.arm_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('arm_pose')) {
        this.arm_pose = initObj.arm_pose
      }
      else {
        this.arm_pose = new geometry_msgs.msg.PointStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PoseAndSizeFeedback
    // Serialize message field [arm_pose]
    bufferOffset = geometry_msgs.msg.PointStamped.serialize(obj.arm_pose, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PoseAndSizeFeedback
    let len;
    let data = new PoseAndSizeFeedback(null);
    // Deserialize message field [arm_pose]
    data.arm_pose = geometry_msgs.msg.PointStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PointStamped.getMessageSize(object.arm_pose);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kinova_msgs/PoseAndSizeFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '84de4ef9896c1cfa9d91c42b0096dbb6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback message
    geometry_msgs/PointStamped arm_pose
    
    ================================================================================
    MSG: geometry_msgs/PointStamped
    # This represents a Point with reference coordinate frame and timestamp
    Header header
    Point point
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PoseAndSizeFeedback(null);
    if (msg.arm_pose !== undefined) {
      resolved.arm_pose = geometry_msgs.msg.PointStamped.Resolve(msg.arm_pose)
    }
    else {
      resolved.arm_pose = new geometry_msgs.msg.PointStamped()
    }

    return resolved;
    }
};

module.exports = PoseAndSizeFeedback;
