// Generated by gencpp from file kinova_msgs/StateAndObject.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_STATEANDOBJECT_H
#define KINOVA_MSGS_MESSAGE_STATEANDOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/Point.h>

namespace kinova_msgs
{
template <class ContainerAllocator>
struct StateAndObject_
{
  typedef StateAndObject_<ContainerAllocator> Type;

  StateAndObject_()
    : status(0)
    , object_pose()
    , object_size()  {
    }
  StateAndObject_(const ContainerAllocator& _alloc)
    : status(0)
    , object_pose(_alloc)
    , object_size(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _object_pose_type;
  _object_pose_type object_pose;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _object_size_type;
  _object_size_type object_size;



  enum {
    START = 1u,
    CANCEL = 2u,
  };


  typedef boost::shared_ptr< ::kinova_msgs::StateAndObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_msgs::StateAndObject_<ContainerAllocator> const> ConstPtr;

}; // struct StateAndObject_

typedef ::kinova_msgs::StateAndObject_<std::allocator<void> > StateAndObject;

typedef boost::shared_ptr< ::kinova_msgs::StateAndObject > StateAndObjectPtr;
typedef boost::shared_ptr< ::kinova_msgs::StateAndObject const> StateAndObjectConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_msgs::StateAndObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_msgs::StateAndObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinova_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'kinova_msgs': ['/home/lh/kinova-ros/src/kinova_msgs/msg', '/home/lh/kinova-ros/devel/.private/kinova_msgs/share/kinova_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_msgs::StateAndObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_msgs::StateAndObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_msgs::StateAndObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5483a7f40ced969438c4b266c24fad97";
  }

  static const char* value(const ::kinova_msgs::StateAndObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5483a7f40ced9694ULL;
  static const uint64_t static_value2 = 0x38c4b266c24fad97ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_msgs/StateAndObject";
  }

  static const char* value(const ::kinova_msgs::StateAndObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n\
uint8 START=1\n\
uint8 CANCEL=2\n\
geometry_msgs/PoseStamped object_pose\n\
geometry_msgs/Point object_size\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::kinova_msgs::StateAndObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.object_pose);
      stream.next(m.object_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateAndObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_msgs::StateAndObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_msgs::StateAndObject_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "object_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.object_pose);
    s << indent << "object_size: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.object_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_STATEANDOBJECT_H
