; Auto-generated. Do not edit!


(cl:in-package kinova_msgs-msg)


;//! \htmlinclude PoseAndSizeGoal.msg.html

(cl:defclass <PoseAndSizeGoal> (roslisp-msg-protocol:ros-message)
  ((object_pose
    :reader object_pose
    :initarg :object_pose
    :type geometry_msgs-msg:PointStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PointStamped))
   (object_size
    :reader object_size
    :initarg :object_size
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point))
   (object_class
    :reader object_class
    :initarg :object_class
    :type cl:string
    :initform ""))
)

(cl:defclass PoseAndSizeGoal (<PoseAndSizeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PoseAndSizeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PoseAndSizeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kinova_msgs-msg:<PoseAndSizeGoal> is deprecated: use kinova_msgs-msg:PoseAndSizeGoal instead.")))

(cl:ensure-generic-function 'object_pose-val :lambda-list '(m))
(cl:defmethod object_pose-val ((m <PoseAndSizeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:object_pose-val is deprecated.  Use kinova_msgs-msg:object_pose instead.")
  (object_pose m))

(cl:ensure-generic-function 'object_size-val :lambda-list '(m))
(cl:defmethod object_size-val ((m <PoseAndSizeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:object_size-val is deprecated.  Use kinova_msgs-msg:object_size instead.")
  (object_size m))

(cl:ensure-generic-function 'object_class-val :lambda-list '(m))
(cl:defmethod object_class-val ((m <PoseAndSizeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:object_class-val is deprecated.  Use kinova_msgs-msg:object_class instead.")
  (object_class m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PoseAndSizeGoal>) ostream)
  "Serializes a message object of type '<PoseAndSizeGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object_pose) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object_size) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'object_class))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'object_class))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PoseAndSizeGoal>) istream)
  "Deserializes a message object of type '<PoseAndSizeGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object_pose) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object_size) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'object_class) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'object_class) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PoseAndSizeGoal>)))
  "Returns string type for a message object of type '<PoseAndSizeGoal>"
  "kinova_msgs/PoseAndSizeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PoseAndSizeGoal)))
  "Returns string type for a message object of type 'PoseAndSizeGoal"
  "kinova_msgs/PoseAndSizeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PoseAndSizeGoal>)))
  "Returns md5sum for a message object of type '<PoseAndSizeGoal>"
  "4c6131538507f7479aa2828d565cd71a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PoseAndSizeGoal)))
  "Returns md5sum for a message object of type 'PoseAndSizeGoal"
  "4c6131538507f7479aa2828d565cd71a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PoseAndSizeGoal>)))
  "Returns full string definition for message of type '<PoseAndSizeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/PointStamped object_pose~%geometry_msgs/Point object_size~%string object_class~%~%================================================================================~%MSG: geometry_msgs/PointStamped~%# This represents a Point with reference coordinate frame and timestamp~%Header header~%Point point~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PoseAndSizeGoal)))
  "Returns full string definition for message of type 'PoseAndSizeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/PointStamped object_pose~%geometry_msgs/Point object_size~%string object_class~%~%================================================================================~%MSG: geometry_msgs/PointStamped~%# This represents a Point with reference coordinate frame and timestamp~%Header header~%Point point~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PoseAndSizeGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object_pose))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object_size))
     4 (cl:length (cl:slot-value msg 'object_class))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PoseAndSizeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PoseAndSizeGoal
    (cl:cons ':object_pose (object_pose msg))
    (cl:cons ':object_size (object_size msg))
    (cl:cons ':object_class (object_class msg))
))
